# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 122ba1173d845a63962153fdc34da56537a3d8aec9234b7cacd568546095abc3fe364245862bd98fefc7177df48bb193ab295c966b075718bbf8e56dbb6ee3bf

test:
  secret_key_base: 223cedf97a2727cf6b6817f998c6e6b76a12b3902ef6561129989fa5d87f0b17e41fa5a4385faf7670effd90aaeb971991023953ae5521b77c144fa5e328b974

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
